export default {
  useLocalApi: true,
  appName: "MIA Application",
  appTitle: "MIA Application",
  appDescription: "MIA application",
  apiRoot: "/api",
  devApiRoot: "/api",
  awardDetails: {
    startDate: "12-12-2020",
    endDate: "15-12-2020",
  },
  reCaptchaKey: "6LfQxtIUAAAAAJyXHUzzKShDXhpzF_TZgpVSN7P0",
  paymentPublicKey: "pk_test_3aa743f7-9a44-4254-9334-7a2c03150753",
  companyLocation: {
    lat: 25.0969085,
    long: 55.155664,
    zoom: 16,
    landMarker: {
      id: "1",
      icon: "./assets/images/markers/marker.svg",
      name: "Media Industry",
      lat: 25.0969085,
      long: 55.155664,
    },
  },
  tickets_enabled: false,
  tickets: [
    {
      locationId: 1,
      mapRef: "https://www.google.com/maps/search/Al-Maydan%20Hotel",
      location: {
        lat: 25.1559204,
        long: 55.2977487,
        zoom: 17,
        landMarker: {
          id: "2",
          icon: "./assets/images/markers/marker.svg",
          name: "Medan hotel",
          lat: 25.1559204,
          long: 55.2977487,
        },
      },
      titleKey: "location1_title",
      title: "Medan hotel",
      descriptionKey: "location1_description",
      description: `TEXT_DEEEDED_HERE`,
      dates: [{ date: "29-05-2020" }, { date: "30-05-2020" }],
    },
    {
      locationId: 2,
      mapRef: "https://www.google.com/maps/search/Dubai+Opera",
      location: {
        lat: 25.1948729,
        long: 55.2654525,
        zoom: 15.76,
        landMarker: {
          id: "1",
          icon: "./assets/images/markers/marker.svg",
          name: "Dubai opera",
          lat: 25.1948729,
          long: 55.2654525,
        },
      },
      titleKey: "location2_title",
      title: "Dubai opera",
      descriptionKey: "location2_description",
      description: `TEXT_DEEEDED_HERE`,
      dates: [
        { date: "20-05-2020" },
        { date: "21-05-2020" },
        { date: "22-05-2020" },
      ],
    },
  ],
  menu: [
    { label: "about_us", route: "/about-us" },
    { label: "members", route: "/members" },
    { label: "news", route: "/news" },
    { label: "program", route: "/timeline" },
    { label: "gallery", route: "/gallery" },
    { label: "shows", route: "/shows" },
    { label: "booths", route: "/booths" },
    { label: "contact_us", route: "/contact-us" },
  ],
  siteShareUrl: "http://miaawards.com",
  social: {
    fb: "https://www.facebook.com/MIAawardArab",
    tw: "https://twitter.com/MIAawardArab",
    in: "https://www.instagram.com/MIAawardarab",
    yt: "https://www.youtube.com/MIAawardarab",
  },
  uploadVideoFileExtension: ["video/mp4"],
  uploadImageFileExtension: ["image/png", "image/jpg", "image/jpeg"],
  MAX_FILE_SIZE: 10485760,
  validationRules: {
    allowed_artwork_years: {
      min: 2019,
      max: 2020,
    },
    phoneExp: /^(\+?\d{0,4})?\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{4}\)?)?$/,
    url: /^((https?):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/,
    passwordStrength: /^(?=.*([A-Z]){1,})(?=.*[!@#$&*]{1,})(?=.*[a-z]{1,}).{6,100}$/,
    videoFiles: ".mp4,.ogg,.webM",
    imageFiles: "image/*",
  },
  files: {
    booth_pdf: "/assets/files/exhibition final.pdf",
  },
};
